name: Jacoco Distributed Exec and Aggregation2

on:
  push:
    branches:
      - "main"

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run tests
        run: |
          mvn '-Dtest=!*IntegrationTest' verify -Djacoco.destFile=exportJacoco/jacoco-fast.exec
      - name: Upload jacoco exec results
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-jacoco
          path: exportJacoco/jacoco-fast.exec

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run tests
        run: |
          mvn '-Dtest=*IntegrationTest' verify -Djacoco.destFile=exportJacoco/jacoco-slow-it.exec
      - name: Upload jacoco exec results
        uses: actions/upload-artifact@v2
        with:
          name: integration-tests-jacoco
          path: exportJacoco/jacoco-slow-it.exec

  merge-jacoco-report:
    name: Jacoco Merge Results
    needs:
      - unit-tests
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: actions/download-artifact@v2
        with:
          name: integration-tests-jacoco
          path: target/
      - uses: actions/download-artifact@v2
        with:
          name: unit-tests-jacoco
          path: target/
      - name: merge results
        run: |
          mvn jacoco:merge package jacoco:report verify -DskipTests=true
      - name: Upload jacoco coverage despite the check result
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage-results-report
          path: target/site/jacoco/
          if-no-files-found: error
